In [1]:
import sys
import os
import pandas as pd
import torch

sys.path.append(os.path.abspath(os.path.join("..")))

from filter.vertical_reduction import (
    transform,
    provenance_column_matching,
    compare,
    provenance_by_hashing,
)

In [2]:
data = {"col1": [1, 2, 3, 4, 5], "col2": [8, 6, 9, 7, 10]}
input_df = pd.DataFrame(data)
input_df

col1  col2
0     1     8
1     2     6
2     3     9
3     4     7
4     5    10

In [3]:
selected_columns = ["col1"]

In [4]:
# retain selected columns:
output_df = transform(input_df, selected_columns, retain=True)
output_df

col1
0     1
1     2
2     3
3     4
4     5

In [5]:
provenance_tensor = provenance_column_matching(input_df, output_df, sparse=True)

print(
    f"Sparse provenance tensor for vertical reduction operation:\n{provenance_tensor}"
)

Sparse provenance tensor for vertical reduction operation:
tensor(indices=tensor([[0]]),
       values=tensor([1]),
       size=(2,), nnz=1, dtype=torch.int8, layout=torch.sparse_coo)


In [6]:
provenance_tensor = provenance_column_matching(input_df, output_df, sparse=False)

print(f"Dense provenance tensor for vertical reduction operation:\n{provenance_tensor}")

Dense provenance tensor for vertical reduction operation:
tensor([1, 0], dtype=torch.int8)


In [7]:
# drop selected columns:
output_df = transform(input_df, selected_columns, retain=False)
output_df

col2
0     8
1     6
2     9
3     7
4    10

In [8]:
provenance_tensor = provenance_column_matching(input_df, output_df, sparse=True)

print(
    f"Sparse provenance tensor for vertical reduction operation:\n{provenance_tensor}"
)

Sparse provenance tensor for vertical reduction operation:
tensor(indices=tensor([[1]]),
       values=tensor([1]),
       size=(2,), nnz=1, dtype=torch.int8, layout=torch.sparse_coo)


In [9]:
provenance_tensor = provenance_column_matching(input_df, output_df, sparse=False)

print(f"Dense provenance tensor for vertical reduction operation:\n{provenance_tensor}")

Dense provenance tensor for vertical reduction operation:
tensor([0, 1], dtype=torch.int8)


In [10]:
input_df = torch.rand(500, 500)
compare(input_df, columns=["col1", "col2", "col498"], retain=True)

INDEX MATCHING

Sparse Tensor Time: 0.000228s

Provenance Sparse Tensor :
tensor(indices=tensor([[  1,   2, 498]]),
       values=tensor([1, 1, 1]),
       size=(500,), nnz=3, dtype=torch.int8, layout=torch.sparse_coo)

Dense Tensor Time: 0.000079s

Provenance dense Tensor :
tensor([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    

In [11]:
input_df = pd.DataFrame({"A": [1, 2], "B": [3, 4], "C": [5, 6]})
output_df = input_df[["A", "C"]]
provenance_column_matching(input_df, output_df, False)

tensor([1, 0, 1], dtype=torch.int8)